### ISSUE TITLE
Detail tab

### ISSUE THREAD

**Issue by darasat** [JoeCherry/my_app#1]
Good day.

This Is a great example.

I am asking how we could keep the bottom tabs for a detail page with this code?

Thank you.

**Comment by JoeCherry** [comment]
Hey, thank you! Can you expand a bit more on your question? Are you asking about pushing a view from one of the widgets within the bottom nav bar or maintaining the state between tab switches?

**Comment by darasat** [comment]
#good day 

I am asking about pushing a view , showing for example a  detail page with products after click on main products tab (changing the route - dart page  ) and keep the bottom navigation bar,

Thanks for your answers,

Regards  n
